Repository GSG-FC02/ReemHebaToDoList, pull requests merged in 2021-03, with the labels that each got.

#7 create js file
  index.js
Labels: awaiting-review

#8 create html
  flamingo.png
  index.html
Labels: approved

#9 create css
  style.css
Labels: approved

#11 test the total app
  index.html
  index.js
  style.css
Labels: approved

#13 edit readme file
  README.md
Labels: approved

#14 update readme file
  README.md
Labels: Done
